remove namespace from Deployment
argoproj/applicationset pull request #403
Opened 2021-11-02 14:03 UTC by ohauer

Remove namespace from Deployment.

I was searching why I got an issue with the following patch and it was because of the namespace in kind Deployment
Looking into the install.yaml of argo-cd and others the difference is the namespace in kind: Deployment in index.yaml.

Two possible pathes:
1. remove the namespace from the Deployment (it is normally given/ overwritten with kustomize)
2. force users to add additional namespace: to the patch (else kustomize will fail and complain with the following message
```
no matches for Id apps_v1_Deployment|~X|argocd-applicationset-controller; failed to find unique target for patch apps_v1_Deployment|argocd-applicationset-controller"
```

```sh
cat > overlay/clusterX/kustomization.yaml <<EOM
kind: Kustomization
namespace: argocd
resources:
- ../../base/

patchesStrategicMerge:
- patch-limits.yaml
EOM

cat > overlay/clusterX/patch-limits.yaml << EOM
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-applicationset-controller
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
EOM
```

2021-11-02 14:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj-labs/applicationset?pullRequest=403) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj-labs/applicationset?pullRequest=403) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj-labs/applicationset?pullRequest=403) it.</sub>

2021-11-04 04:10 UTC, jgwest commented
@ohauer The file you are proposing to change in this PR is auto-generated by `make manifests`, using kustomize, and should not modified directly. 

Note that Argo CD's `install.yaml` also hardcodes a namspace: https://github.com/argoproj/argo-cd/blob/0d4e40ed6a7c5f3854d47f11f30b6c0606548601/manifests/install.yaml#L2821

I'm not sure what you're trying to accomplish: are you trying to run Argo CD in a different namespace?

2021-11-04 13:30 UTC, ohauer commented
I found this by setting resource limits/requests to the kustomize based deployments. for argocd the sample patch from initial request works but not for the applicationcontroller.
For applicationcontroller the patch requires additional the namespace in the patch else kustomize will complain the patch is not spacific enough.

You are right, argo-cd also uses namespace but **only in ClusterRoleBinding and in context to the ServiceAccount** (Line 2821 and 2838) and nowhere else.

2021-11-16 16:31 UTC, jgwest requested changes
Not sure this is the right approach, see above.

2022-01-24 15:56 UTC, jgwest commented
Fixed by https://github.com/argoproj/applicationset/pull/474

2022-01-24 15:56 UTC, closed without merging