Remove Argo CD integration, and update Argo CD dependencies
argoproj/applicationset pull request #502
Opened 2022-02-14 13:57 UTC by jgwest

This PR:
- Updates the Go version to 1.17
- Updates Go module dependencies, and Dockerfile base image, to same versions as Argo CD 
- Removes the integrated ApplicationSet+Argo CD install YAML (this is now handled at the Argo CD level)
    - Updates docs
    - Removes generated YAML, and kustomize
    - Updates corresponding build/release shell scripts
- Regenerates ApplicationSet/Argo CD manifests, to latest from 2.3.0-rc5

2022-02-16 16:11 UTC, crenshaw-dev requested changes

2022-02-16 16:11 UTC, crenshaw-dev commented on docs/Getting-Started.md
> -### B) Install ApplicationSet and Argo CD together
`C` below should be changed to `B`.

2022-02-16 16:11 UTC, crenshaw-dev commented on go.mod
> +require (
Just for my own knowledge: is this just a pinning mechanism for transient dependencies, in order to get (relatively) deterministic builds?

2022-02-16 16:11 UTC, crenshaw-dev commented on hack/generate-manifests.sh
> +# Verify that the GitHub actions is targetting the expected Argo CD version
```suggestion
# Verify that the GitHub actions are targeting the expected Argo CD version
```

2022-02-25 03:58 UTC, wtam2018 commented on hack/generate-manifests.sh
> +# Verify that the GitHub actions is targetting the expected Argo CD version
```suggestion
# Verify that the GitHub Actions is targeting the expected Argo CD version
```

2022-02-25 06:25 UTC, wtam2018 approved these changes
LGTM
thanks @jgwest !

2022-02-25 06:26 UTC, merged